### ISSUE TITLE
ハンバーガーメニューの作成

### ISSUE THREAD

**Issue by yugeta** [nakamura0907/design-kit#8]
```
Date : 2022.05.20
Author : Yugeta.Koji
```

# 概要
- モバイルページで必須のメニューtoggle表示の役割のハンバーガーアイコンと、出し入れされるメニュー（セットでハンバーガーメニュー）
- cssだけで実装できるので、javascriptを使わない簡単構成で構築
- 色々なページに適用しやすい様に、HTML構成と、css構成、紐づくclass名などの仕様検討

**Comment by nakamura0907** [comment]
class名には`dk-`というプレフィックスの追加をお願いします。

例
```
<div class="dk-hamburger"></div>
```
